apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{labelAppName}}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: {{appName}}
        version: {{version}}
        name: {{appName}}
    spec:
      containers:
      - name: {{containerName}}
        image: {{dockerOrg}}/{{appName}}:{{version}}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8888
---
##################################################################################################
# config service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: {{appName}}
  labels:
    name: {{appName}}
    visualize: "true"
spec:
  ports:
    - port: 8888
  selector:
    name: {{appName}}
---
###########################################################################
# Ingress resource (gateway)
##########################################################################
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{appName}}-gateway
  annotations:
    kubernetes.io/ingress.class: "istio"
spec:
  rules:
  - http:
      paths:
      - path: /{{appName}}health
        backend:
          serviceName: {{appName}}
          servicePort: 8888    
---