apiVersion: v1
kind: Service
metadata:
  name: {{appName}}
  labels:
    name: {{appName}}
    visualize: "true"
spec:
  ports:
    - port: 8888
  selector:
    name: {{appName}}
---
###########################################################################
# Ingress resource (gateway)
##########################################################################
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{appName}}gateway
  annotations:
    kubernetes.io/ingress.class: "istio"
spec:
  rules:
  - http:
      paths:
      - path: /{{appName}}health
        backend:
          serviceName: {{appName}}
          servicePort: 8888    
---