##################################################################################################
# config service
##################################################################################################
apiVersion: v1
kind: ReplicationController
metadata:
  name: configserver
spec:
  replicas: 1
  selector:
    app: configserver
  template:
    metadata:
      labels:
        app: configserver
    spec:
      dnsPolicy: ClusterFirst
      containers:
      - name: service
        image: gcr.io/serious-hold-175505/config-server-v1
        env:
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: TARGET_CONFIG
          value: configserver
        args:
        - "-addr=:8888"
        ports:
        - name: service
          containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: configserver
spec:
  selector:
    app: configserver
  clusterIP: None
  ports:
  - name: http
    port: 8888